### ISSUE TITLE
AppImage support (pCloud and other apps)

### ISSUE THREAD

**Issue by phocean** [bilelmoussaoui/Hardcode-Tray#608]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Ubuntu 19.10`
- Gtk version : `3.24`
- Inkscape version : `0.92..4`
- Application name :  `pCloud`
- Application version : `1.7.1`

### Expected behavior and actual behavior

Harcode-tray is expected to detect pCloud installation and patch it.

Actually, it's not detecting it and not fixing the icon.

On my environment, it worked successfully for Signal and Skype.

**Comment by phocean** [comment]
I managed to patch it but I had to :

1. Uncompress the appimage to /opt/pcloud/
2. Apply Hardcode-tray
3. Repackage the appimage

**Comment by varlesh** [comment]
> Uncompress the appimage to /opt/pcloud/

No. First need integrate appimage to system, because integrated app create binary file for run and asar resources for tray icons. After this need unpack integrated appimage to /opt/pcloud/

> Repackage the appimage

Not needed.

all these actions doesn't make sense, because appimage app it's portable app. And how update this? 

But this possible doing once:
![image](https://user-images.githubusercontent.com/8083855/69023562-a1c74b00-09d8-11ea-8df3-445566400467.png)

**Comment by phocean** [comment]
Sorry but I do not understand well your English.

What I take:

- I don't care if my workaround is not optimal, I spent 5 min for it and it works. I never said it would survive an update or was a fix.

- You don't answer to the issue though: it did not work. Please fix it.

**Comment by varlesh** [comment]
Try it:
```
# Remove old desktop file
rm ~/.local/share/applications/appimagekit-pcloud.desktop

# Download fresh pCloud version from site and extract appimage
./pcloud --appimage-extract

# Copy app to /opt
sudo cp -R squashfs-root /opt/pcloud
sudo chmod -R 755 /opt/pcloud

# Run application for generation new desktop file on ~/.local/share/applications
/opt/pcloud/AppRun

# Close application and run HardcodeTray
sudo -E hardcode-tray -ct RSVGConvert -o pcloud-drive
```

**Comment by phocean** [comment]
Yes, it works.

So should I leave the extracted squashfs directory as-is?
I thought it would not work with future updates, but it's nice if I was wrong.

Thank you.

**Comment by varlesh** [comment]
I don't know how this will be worked on future, because application now distibuted only as portable appimage...

**Comment by phocean** [comment]
Just tested with today's update to version 1.7.2 : as I expected, it does not work.

Please re-open this issue, because as long as pCloud is "supported", it does not work so it's an issue.

**Comment by varlesh** [comment]
Follow the instructions again. I warned about that. Application distributed as portable appimage - we can't doing anything.
Maybe for block auto updates need added URL to black list. For example:
`sudo sh -c "echo '127.0.0.1 https://api.pcloud.com' >> /etc/hosts"`

**Comment by phocean** [comment]
I am not here for instructions but to report a bug, do you understand ?

The tool claims support for pCloud, but it does not work. This is a bug.

It can be solved:

- either by implementing support for Appimages, which should not be too hard (unpack, modify, repack squashfs) ;

- updating the documentation ;

- or by withdrawing support for pCloud (and other Appimages).

But you cannot reasonably:

- close the issue as-is;
- tell users to not update, which is a **VERY, VERY bad idea** as updates fix bugs and security issues.

Nowadays, in no way a computer professional should advice users to not update sensitive software!!

**Comment by varlesh** [comment]
Hey, hey stop. It's only tray icons. Do not worry so much ))
I say about AUTO UPDATES. If you want control tray icon YOU CAN update when you want. So that it is not unpredictable for you.
Appimages not supported. 
Appimage - it's portable package and this impossible, because script find binary on root file system for check installed application.
IF DEVELOPER PCLOUD NOT SUPPORT DEB, RPM - it's not our problem.

I'm only supporter and tried to help you.
Main developer @bilelmoussaoui not active for hardcode-tray now.
If you know Python - welcome PR! And add support Appimage, FlatPak, Snap and others problem apps.

**Comment by phocean** [comment]
The instructions break the updates, automatic or not, so tha's the problem.

I get what you say about contribution, but first do not close this issue. Which you did in spite of not being the maintainer.

How can it be fixed if it's not visible?

**Comment by phocean** [comment]
Note that I might PR when I have time, but your attitude is not encouraging me.

**Comment by bilelmoussaoui** [comment]
@phocean I gave @varlesh the maintainer rights. So please, respect whatever decision he takes.

**Comment by phocean** [comment]
@bilelmoussaoui 

Where do you see a lack of respect?
What the purpose of this comment? Do you mean we do not have the right to discuss?

I only see a discussion and some usual request for handling such cases.

**Comment by phocean** [comment]
Now honestly you might take it for a lack of respect: that's too much headaches for a project of that importance.
I am done. Good luck.
