### ISSUE TITLE
Support New Programs

### ISSUE THREAD

**Issue by btd1337** [bilelmoussaoui/Hardcode-Tray#631]
First of all, congratulations to developers for this great project.

My question is as follow:

Would It be possible to add support for the following applications?

- [x] Microsoft Teams
- [x] Slack
- [ ] PCloud

Thanks in advance!

**Comment by varlesh** [comment]
MS Teams here:
https://github.com/bilelmoussaoui/Hardcode-Tray/blob/master/data/database/teams.json
Slack now impossible, because used Base64 image:
https://github.com/bilelmoussaoui/Hardcode-Tray/issues/605
pCloud not support with appimage:
https://github.com/bilelmoussaoui/Hardcode-Tray/issues/608
