### ISSUE TITLE
[Icon Request]: Barrier

### ISSUE THREAD

**Issue by luccacondratiuk** [bilelmoussaoui/Hardcode-Tray#694]
### Specifications
- Hardcode-Tray version : `4.3-3`
- Distribution : `Arch Linux`
- Application name :  `Barrier` - [Github repo](https://github.com/debauchee/barrier)
- Application version : `2.3.3-1`

**Comment by acarasimon96** [comment]
Hi there, I recently ran into this behavior and even reported about it in PapirusDevelopmentTeam/papirus-icon-theme#2793, but installing the [Git version from the AUR](https://aur.archlinux.org/packages/barrier-git) fixed it for me. Unfortunately, the [commit](https://github.com/debauchee/barrier/commit/95afed5256aff94034a858bcbf072fd5d6b13b92#diff-43c9ca260e8282de37dbe7f44768f6fd9d857f8642663fed14f3a1e7c514a8ba) which addressed the lack of system theme support for Barrier's tray icons got pushed months after the latest stable release dated July 14, 2020, so if you're not comfortable building the Git version, I suggest you wait for the next stable release to land.

In any case, please do keep this issue closed because this has already been solved upstream, and using Hardcode Tray on Barrier is no longer necessary, at least in my opinion.
